import { defineTable } from "convex/server";
import { v } from "convex/values";

/** Per-owner TallyPrime HTTP/XML gateway connection settings. */
export const tallySettings = defineTable({
  ownerId: v.id("users"),
  /** Reachable URL for Tally's HTTP gateway, e.g. http://1.2.3.4:9000. Only used for the direct-connection method. */
  gatewayUrl: v.optional(v.string()),
  /** Company name reported by Tally on last successful test, if any */
  companyName: v.optional(v.string()),
  lastTestedAt: v.optional(v.string()),
  lastTestStatus: v.optional(v.union(v.literal("success"), v.literal("failure"))),
  lastTestError: v.optional(v.string()),
  /** Secret token the local bridge script presents to authenticate uploads. Opaque, generated by the app. */
  bridgeToken: v.optional(v.string()),
  bridgeTokenCreatedAt: v.optional(v.string()),
  bridgeLastUploadAt: v.optional(v.string()),
}).index("by_owner", ["ownerId"]).index("by_bridge_token", ["bridgeToken"]);
