import { useState } from "react";
import { FileText, Loader2, Upload } from "lucide-react";
import { toast } from "sonner";
import { parseSpreadsheetFile } from "@/lib/file-parser.ts";
import { importMigrationPurchaseInvoices } from "@/lib/migration-api.ts";
import { Button } from "@/components/ui/button.tsx";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card.tsx";
import { Input } from "@/components/ui/input.tsx";

const fields = ["vendorName", "invoiceNumber", "date", "dueDate", "description", "quantity", "rate", "gstRate", "tds", "narration"];
const aliases: Record<string, string[]> = { vendorName: ["vendor_name", "vendor", "supplier", "party_name"], invoiceNumber: ["invoice_number", "invoice_no", "bill_no"], date: ["date", "invoice_date", "bill_date"], dueDate: ["due_date", "payment_due"], description: ["description", "item", "particulars", "narration"], quantity: ["quantity", "qty", "units"], rate: ["rate", "unit_price", "unit_rate", "price"], gstRate: ["gst_rate", "gst", "tax_rate"], tds: ["tds", "tds_amount"], narration: ["narration", "notes", "remarks"] };
const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
export default function MigrationInvoiceImportPanel() {
  const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [headers, setHeaders] = useState<string[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [stage, setStage] = useState<"idle" | "mapping" | "preview" | "importing" | "done">("idle"); const [valid, setValid] = useState<Record<string, unknown>[]>([]); const [errors, setErrors] = useState<string[]>([]); const [imported, setImported] = useState(0);
  const load = async (file: File) => { try { const result = await parseSpreadsheetFile(file); if (result.parseErrors.length) throw new Error(result.parseErrors[0]); const fileHeaders = Object.keys(result.rows[0] || {}); const next: Record<string, string> = {}; for (const field of fields) { const match = fileHeaders.find((header) => aliases[field].includes(normalize(header))); if (match) next[field] = match; } setRows(result.rows); setHeaders(fileHeaders); setMapping(next); setStage("mapping"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not read invoice workbook"); } };
  const preview = () => { const mapped = rows.map((row) => Object.fromEntries(Object.entries(mapping).map(([field, header]) => [field, row[header]]))); const nextErrors: string[] = []; const nextValid = mapped.filter((row, index) => { const missing = ["vendorName", "invoiceNumber", "date", "description", "quantity", "rate"].filter((field) => !String(row[field] ?? "").trim()); if (missing.length) { nextErrors.push(`Row ${index + 2}: missing ${missing.join(", ")}`); return false; } return true; }); setErrors(nextErrors); setValid(nextValid); setStage("preview"); };
  const submit = async () => { setStage("importing"); try { const result = await importMigrationPurchaseInvoices(valid); setImported(result.imported); setStage("done"); toast.success(`Imported ${result.imported} invoices`); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not import invoices"); setStage("preview"); } };
  return <Card><CardHeader><CardTitle>Purchase Invoices Import</CardTitle></CardHeader><CardContent className="space-y-4">{stage === "idle" && <label className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-lg border-2 border-dashed p-10 text-center hover:border-primary"><Upload className="size-8 text-muted-foreground" /><span className="text-sm font-medium">Choose purchase invoice spreadsheet</span><span className="text-xs text-muted-foreground">CSV, XLSX, XLS, or ODS</span><input type="file" accept=".csv,.xlsx,.xls,.ods" className="sr-only" onChange={(event) => event.target.files?.[0] && void load(event.target.files[0])} /></label>}{stage === "mapping" && <div className="space-y-3"><p className="text-sm text-muted-foreground">Map invoice columns. Required fields are marked with *.</p>{fields.map((field) => <div className="grid grid-cols-[140px_1fr] items-center gap-2" key={field}><span className="text-xs font-medium">{field}{["vendorName","invoiceNumber","date","description","quantity","rate"].includes(field) ? " *" : ""}</span><select className="h-8 rounded-md border bg-background px-2 text-sm" value={mapping[field] || ""} onChange={(e) => setMapping((current) => ({ ...current, [field]: e.target.value }))}><option value="">Not mapped</option>{headers.map((header) => <option key={header}>{header}</option>)}</select></div>)}<Button onClick={preview}>Preview import</Button></div>}{stage === "preview" && <div className="space-y-4"><div className="flex gap-3 rounded-lg bg-muted/40 p-3 text-sm"><span>{valid.length} valid rows</span><span>{errors.length} invalid rows</span></div>{errors.length > 0 && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900">{errors.slice(0, 10).map((error) => <p key={error}>{error}</p>)}</div>}<Button onClick={() => void submit()} disabled={!valid.length}>Import {valid.length} invoices</Button></div>}{stage === "importing" && <div className="flex justify-center gap-2 py-8 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Importing invoices...</div>}{stage === "done" && <div className="py-8 text-center"><FileText className="mx-auto mb-3 size-8 text-primary" /><p className="font-semibold">{imported} invoices imported as drafts.</p><Input className="mx-auto mt-4 max-w-xs" value="Import another file" readOnly onClick={() => { setStage("idle"); setRows([]); setValid([]); }} /></div>}</CardContent></Card>;
}
