import { useState } from "react";
import { toast } from "sonner";
import { createMigrationConstructionExpense } from "@/lib/migration-api.ts";
import { Button } from "@/components/ui/button.tsx";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog.tsx";
import { Input } from "@/components/ui/input.tsx";

export default function MigrationExpenseDialog({ open, onOpenChange, projectId }: { open: boolean; onOpenChange: (open: boolean) => void; projectId: string }) {
  const [description, setDescription] = useState(""); const [category, setCategory] = useState("material"); const [vendor, setVendor] = useState(""); const [amount, setAmount] = useState(""); const [expenseDate, setExpenseDate] = useState(new Date().toISOString().slice(0, 10)); const [saving, setSaving] = useState(false);
  const submit = async () => { if (!description.trim() || !amount) { toast.error("Description and amount are required"); return; } setSaving(true); try { await createMigrationConstructionExpense(projectId, { description, category, vendor: vendor || undefined, amount: Number(amount), expenseDate }); toast.success("Expense recorded"); onOpenChange(false); window.location.reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not record expense"); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Record expense</DialogTitle></DialogHeader><div className="space-y-3"><Input placeholder="Description *" value={description} onChange={(e) => setDescription(e.target.value)} /><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm" value={category} onChange={(e) => setCategory(e.target.value)}><option value="material">Material</option><option value="labour">Labour</option><option value="approvals">Approvals</option><option value="legal">Legal</option><option value="marketing">Marketing</option><option value="other">Other</option></select><Input placeholder="Vendor" value={vendor} onChange={(e) => setVendor(e.target.value)} /><div className="grid grid-cols-2 gap-3"><Input type="number" placeholder="Amount (₹) *" value={amount} onChange={(e) => setAmount(e.target.value)} /><Input type="date" value={expenseDate} onChange={(e) => setExpenseDate(e.target.value)} /></div></div><DialogFooter><Button variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={saving}>{saving ? "Saving..." : "Record expense"}</Button></DialogFooter></DialogContent></Dialog>;
}
