import { useEffect, useState } from "react";
import { toast } from "sonner";
import { convertMigrationMaterialRequest, migrationGet } from "@/lib/migration-api.ts";
import { Button } from "@/components/ui/button.tsx";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog.tsx";
import { Input } from "@/components/ui/input.tsx";

type Props = { request: any | null; open: boolean; onOpenChange: (open: boolean) => void };
export default function MigrationConvertToPoDialog({ request, open, onOpenChange }: Props) {
  const [vendors, setVendors] = useState<any[]>([]); const [vendorId, setVendorId] = useState(""); const [rates, setRates] = useState<string[]>([]); const [delivery, setDelivery] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!open || !request) return; migrationGet<any[]>("/api/payables/vendors").then(setVendors).catch(() => setVendors([])); setRates((request.lines || []).map((line: any) => String(line.rate || ""))); }, [open, request]);
  const submit = async () => { if (!vendorId || rates.some((rate) => !rate || Number(rate) < 0)) { toast.error("Select a vendor and enter every line rate"); return; } setSaving(true); try { await convertMigrationMaterialRequest(request._id, { vendorId, rates: rates.map(Number), expectedDeliveryDate: delivery || undefined }); toast.success("Purchase order created"); onOpenChange(false); window.location.reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not convert request"); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>Convert to Purchase Order</DialogTitle><p className="text-sm text-muted-foreground">Select a vendor and enter the rate for each requested material.</p></DialogHeader><div className="space-y-4"><select className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm" value={vendorId} onChange={(e) => setVendorId(e.target.value)}><option value="">Select vendor *</option>{vendors.filter((vendor) => vendor.isActive !== false).map((vendor) => <option key={vendor._id} value={vendor._id}>{vendor.name}{vendor.gstin ? ` - ${vendor.gstin}` : ""}</option>)}</select><Input type="date" value={delivery} onChange={(e) => setDelivery(e.target.value)} placeholder="Expected delivery date" /><div className="space-y-2">{(request?.lines || []).map((line: any, index: number) => <div className="grid grid-cols-[1fr_100px] items-center gap-2" key={line._id || index}><div><p className="text-sm font-medium">{line.description}</p><p className="text-xs text-muted-foreground">{line.quantity} {line.unit}</p></div><Input type="number" min="0" placeholder="Rate" value={rates[index] || ""} onChange={(e) => setRates((current) => current.map((rate, i) => i === index ? e.target.value : rate))} /></div>)}</div></div><DialogFooter><Button variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={saving}>{saving ? "Creating..." : "Create Purchase Order"}</Button></DialogFooter></DialogContent></Dialog>;
}
