import { useEffect, useState } from "react";
import { toast } from "sonner";
import { convertMigrationMaterialRequest, createMigrationVendor, migrationGet } from "@/lib/migration-api.ts";
import { Button } from "@/components/ui/button.tsx";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog.tsx";
import { Input } from "@/components/ui/input.tsx";
import { SearchableSelect } from "@/components/ui/searchable-select.tsx";

type Props = { request: any | null; open: boolean; onOpenChange: (open: boolean) => void };
export default function MigrationConvertToPoDialog({ request, open, onOpenChange }: Props) {
  const [vendors, setVendors] = useState<any[]>([]); const [vendorId, setVendorId] = useState(""); const [rates, setRates] = useState<string[]>([]); const [delivery, setDelivery] = useState(""); const [saving, setSaving] = useState(false); const [newVendorName, setNewVendorName] = useState(""); const [creatingVendor, setCreatingVendor] = useState(false);
  useEffect(() => { if (!open || !request) return; migrationGet<any[]>("/api/payables/vendors").then(setVendors).catch(() => setVendors([])); setRates((request.lines || []).map((line: any) => String(line.rate || ""))); }, [open, request]);
  const submit = async () => { if (!vendorId || rates.some((rate) => !rate || Number(rate) < 0)) { toast.error("Select a vendor and enter every line rate"); return; } setSaving(true); try { await convertMigrationMaterialRequest(request._id, { vendorId, rates: rates.map(Number), expectedDeliveryDate: delivery || undefined }); toast.success("Purchase order created"); onOpenChange(false); window.location.reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not convert request"); } finally { setSaving(false); } };
  const createVendor = async () => { if (!newVendorName.trim()) return; setCreatingVendor(true); try { const vendor = await createMigrationVendor({ name: newVendorName.trim(), category: "material_supplier" }); setVendors((current) => [...current, vendor]); setVendorId(vendor._id); setNewVendorName(""); toast.success("Vendor created and selected"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create vendor"); } finally { setCreatingVendor(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>Convert to Purchase Order</DialogTitle><p className="text-sm text-muted-foreground">Search for a vendor or create one, then confirm rates for each requested material.</p></DialogHeader><div className="space-y-4"><SearchableSelect value={vendorId} onValueChange={setVendorId} options={vendors.filter((vendor) => vendor.isActive !== false).map((vendor) => ({ value: vendor._id, label: vendor.name, sub: vendor.gstin, keywords: `${vendor.name} ${vendor.gstin ?? ""}` }))} placeholder="Select vendor *" searchPlaceholder="Type vendor name…" /><div className="flex gap-2"><Input placeholder="New vendor name" value={newVendorName} onChange={(e) => setNewVendorName(e.target.value)} /><Button type="button" variant="secondary" onClick={() => void createVendor()} disabled={!newVendorName.trim() || creatingVendor}>{creatingVendor ? "Adding..." : "Create vendor"}</Button></div><Input type="date" value={delivery} onChange={(e) => setDelivery(e.target.value)} placeholder="Expected delivery date" /><div className="space-y-2">{(request?.lines || []).map((line: any, index: number) => <div className="grid grid-cols-[1fr_100px] items-center gap-2" key={line._id || index}><div><p className="text-sm font-medium">{line.description}</p><p className="text-xs text-muted-foreground">{line.quantity} {line.unit}</p></div><Input type="number" min="0" placeholder="Rate" value={rates[index] || ""} onChange={(e) => setRates((current) => current.map((rate, i) => i === index ? e.target.value : rate))} /></div>)}</div></div><DialogFooter><Button variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={saving}>{saving ? "Creating..." : "Create Purchase Order"}</Button></DialogFooter></DialogContent></Dialog>;
}
