import { useEffect, useState } from "react";
import { toast } from "sonner";
import { createMigrationAccount, updateMigrationAccount } from "@/lib/migration-api.ts";
import { Button } from "@/components/ui/button.tsx";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog.tsx";
import { Input } from "@/components/ui/input.tsx";

type Account = { _id: string; code: string; name: string; type: string; group: string; openingBalance?: number; description?: string };
const groups: Record<string, string[]> = { asset: ["bank_and_cash", "receivables", "current_assets", "fixed_assets"], liability: ["payables", "current_liabilities", "loans"], income: ["sales_income", "other_income"], expense: ["direct_expenses", "indirect_expenses", "finance_charges"], equity: ["capital", "reserves"] };

export default function MigrationAccountDialog({ open, onOpenChange, account }: { open: boolean; onOpenChange: (open: boolean) => void; account?: Account }) {
  const [code, setCode] = useState(""); const [name, setName] = useState(""); const [type, setType] = useState("asset"); const [group, setGroup] = useState("bank_and_cash"); const [openingBalance, setOpeningBalance] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!open) return; setCode(account?.code ?? ""); setName(account?.name ?? ""); setType(account?.type ?? "asset"); setGroup(account?.group ?? "bank_and_cash"); setOpeningBalance(account?.openingBalance?.toString() ?? ""); }, [open, account]);
  const submit = async () => { if (!name.trim() || (!account && !code.trim())) { toast.error(account ? "Account name is required" : "Code and account name are required"); return; } setSaving(true); try { if (account) await updateMigrationAccount(account._id, { name, openingBalance: openingBalance ? Number(openingBalance) : undefined }); else await createMigrationAccount({ code, name, type, group, openingBalance: openingBalance ? Number(openingBalance) : undefined }); toast.success(account ? "Account updated" : "Account created"); onOpenChange(false); window.location.reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save account"); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{account ? "Edit Account" : "New Account"}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3"><Input placeholder="Code" value={code} disabled={!!account} onChange={(e) => setCode(e.target.value)} /><Input placeholder="Account name" value={name} onChange={(e) => setName(e.target.value)} />{!account && <><select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={type} onChange={(e) => { setType(e.target.value); setGroup(groups[e.target.value][0]); }}><option value="asset">Asset</option><option value="liability">Liability</option><option value="income">Income</option><option value="expense">Expense</option><option value="equity">Equity / Capital</option></select><select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={group} onChange={(e) => setGroup(e.target.value)}>{(groups[type] ?? []).map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></>}<Input className="col-span-2" type="number" placeholder="Opening balance (₹)" value={openingBalance} onChange={(e) => setOpeningBalance(e.target.value)} /></div><DialogFooter><Button variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={saving}>{saving ? "Saving..." : account ? "Save changes" : "Create account"}</Button></DialogFooter></DialogContent></Dialog>;
}