import { useRef, useState } from "react";
import { FileUp, Upload } from "lucide-react";
import { toast } from "sonner";
import { parseTdsDeducteeWorkbook, type TdsDeducteeImportRow } from "@/lib/tds-deductee-import.ts";
import { importMigrationTdsDeductees } from "@/lib/migration-api.ts";
import { Button } from "@/components/ui/button.tsx";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog.tsx";
import { Badge } from "@/components/ui/badge.tsx";

export default function MigrationDeducteeImport() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false); const [fileName, setFileName] = useState(""); const [rows, setRows] = useState<TdsDeducteeImportRow[]>([]); const [saving, setSaving] = useState(false);
  const handleFile = async (file: File) => { try { const parsed = parseTdsDeducteeWorkbook(await file.arrayBuffer()); if (!parsed.length) throw new Error("Could not find valid Name and PAN rows"); setFileName(file.name); setRows(parsed); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not read deductee workbook"); } };
  const submit = async () => { setSaving(true); try { const result = await importMigrationTdsDeductees(rows); toast.success(`Imported ${result.imported}, updated ${result.updated}, skipped ${result.skipped}`); setOpen(false); setRows([]); setFileName(""); window.location.reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not import deductees"); } finally { setSaving(false); } };
  return <><Button size="sm" variant="secondary" onClick={() => setOpen(true)}><Upload className="size-4" />Import Deductees</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Import Deductees from Excel</DialogTitle><p className="text-sm text-muted-foreground">Upload the Form 140 [26Q] Deductee workbook. Name and PAN are required.</p></DialogHeader><div className="space-y-4">{!rows.length ? <label className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-lg border-2 border-dashed p-10 text-center hover:border-primary"><FileUp className="size-8 text-muted-foreground" /><span className="text-sm font-medium">Choose Excel workbook</span><span className="text-xs text-muted-foreground">.xlsx or .xls</span><input ref={inputRef} type="file" accept=".xlsx,.xls" className="sr-only" onChange={(e) => e.target.files?.[0] && void handleFile(e.target.files[0])} /></label> : <><div className="flex items-center gap-2"><Badge variant="secondary">{fileName}</Badge><span className="text-sm text-muted-foreground">{rows.length} valid deductees</span></div><div className="max-h-64 overflow-auto rounded-lg border"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="px-3 py-2">Name</th><th className="px-3 py-2">PAN</th><th className="px-3 py-2">Validation</th><th className="px-3 py-2">PAN holder</th></tr></thead><tbody className="divide-y">{rows.slice(0, 50).map((row) => <tr key={row.pan}><td className="px-3 py-2">{row.name}</td><td className="px-3 py-2 font-mono text-xs">{row.pan}</td><td className="px-3 py-2 text-xs">{row.panValidationStatus || "-"}</td><td className="px-3 py-2 text-xs">{row.panHolderName || "-"}</td></tr>)}</tbody></table></div></>}</div><DialogFooter><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={saving || !rows.length}>{saving ? "Importing..." : "Import Deductees"}</Button></DialogFooter></DialogContent></Dialog></>;
}
